language: node_js
node_js:
  - "lts/*"
addons:
  apt:
    sources:
      - sourceline: "deb http://dl.google.com/linux/chrome/deb/ stable main"
        key_url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
    packages:
      - google-chrome-stable
before_script:
  - yarn install
script:
  - yarn run lint
  - yarn test
